apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secgovs.mycompany.apis.com
  annotations:
    type: apigee-sharedflow-template
spec:
  group: mycompany.apis.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              enabled:
                type: boolean
              displayName:
                type: string
              filters:
                items:
                  properties:
                    group:
                      type: string
                    kind:
                      enum:
                      - SpikeArrest
                      - JS
                      - ResponseCache
                      type: string
                    name:
                      type: string
                  required:
                  - kind
                  - name
                  type: object
                type: array
  scope: Cluster
  names:
    plural: secgovs
    singular: secgov
    kind: Secgov
    shortNames:
    - secgov
