apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: internal-http
  namespace: default
spec:
  gatewayClassName: gke-l7-rilb
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
      kinds:
      - kind: HTTPRoute
