apiVersion: apim.googleapis.com/v1alpha1
kind: APIMExtensionPolicy
metadata:
 name: apim-extension
spec:
  location: us-west1
  failOpen: false
  timeout: 1000ms
  targetRef:
     name: internal-http
     kind: Gateway
     namespace: default
    #  extensionServerRef: # depends on Gateway that routes to the apigee adapter service
    #     name: apigee-adapter-gateway
    #     kind: Gateway
    #     namespace: apigee
