apiVersion: apim.googleapis.com/v1alpha1
kind: APIProduct
metadata:
 name: demoproduct
 namespace: apigee
spec:
  name: demoproduct
  approvalType: auto
  description: Demo product created via k8s controller
  displayName: Demo Product
  analytics:
    enabled: true
  enforcementRefs:
  - name: global-ext-lb1-apim-policy 
    kind: APIMExtensionPolicy
    group: apim.googleapis.com
    namespace: apigee
  attributes:
  - name: access
    value: public
