apiVersion: apim.googleapis.com/v1alpha1
kind: APIOperationSet
metadata:
  name: foo-set
  namespace: apigee
spec:
  apiProductRefs:
  - name: demoproduct
    kind: APIProduct
    group: apim.googleapis.com
    namespace: apigee
  quota:
    limit: 5
    interval: 1
    timeUnit: minute
  restOperations:
   - name: ListFoo
     path: "/foo"
     methods:
     - GET
   - name: GetFoo
     path: "/foo/*"
     methods:
     - GET
